## Logistic Regression on Iris Dataset

In [1]:
from sklearn.datasets import load_iris

In [2]:
dataset=load_iris()

In [4]:
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [8]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [9]:
import numpy as np
import pandas as pd


In [15]:
#creating a Dataframe
df=pd.DataFrame(dataset.data,columns=dataset.feature_names)

In [16]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [24]:
dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [25]:
df['class']=dataset.target

In [27]:
df['class'].unique()

array([0, 1, 2])

In [29]:
#logistic regression on Binary classification so we will consider only 2 classes in target
df_copy=df[df['class']!=2]

In [31]:
df_copy['class'].unique()

array([0, 1])

In [35]:
#independent and dependent features
X=df_copy.iloc[:,:-1]
y=df_copy['class']

In [37]:
from sklearn.model_selection import train_test_split

In [38]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [39]:
from sklearn.linear_model import LogisticRegression

In [40]:
classification=LogisticRegression()

In [41]:
classification.fit(X_train,y_train)

LogisticRegression()

In [42]:
y_pred=classification.predict(X_test)

In [43]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

In [44]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [45]:
confusion_matrix(y_test,y_pred)

array([[12,  0],
       [ 0,  8]])

In [47]:
accuracy_score(y_test,y_pred)

1.0

In [50]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [51]:
from sklearn.model_selection import KFold

In [54]:
cv=KFold(n_splits=10)

In [55]:
cv

KFold(n_splits=10, random_state=None, shuffle=False)

In [56]:
from sklearn.model_selection import cross_val_score

In [58]:
score=cross_val_score(classification,X_train,y_train,cv=cv)

In [59]:
score

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [61]:
#Average of the scores
np.mean(score)

1.0

## Hyperparameter tunning with gridsearchcv

In [63]:
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings('ignore')

In [68]:
parameters={'penalty':('l1','l2','elasticnet'), 'C':[1,10,30,20],'solver':('lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'),'multi_class':('auto', 'ovr', 'multinomial')}

In [69]:
classifier=LogisticRegression()

In [70]:
clf=GridSearchCV(classifier,param_grid=parameters,cv=5)

In [71]:
clf.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 10, 30, 20],
                         'multi_class': ('auto', 'ovr', 'multinomial'),
                         'penalty': ('l1', 'l2', 'elasticnet'),
                         'solver': ('lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga')})

In [72]:
clf.best_params_

{'C': 1, 'multi_class': 'auto', 'penalty': 'l1', 'solver': 'liblinear'}

In [73]:
clf.best_score_

1.0

In [75]:
## now we shall train and prdict predict data based on best paramaeter achieved by GridsearchCV
classification=LogisticRegression(penalty='l1',C=1,multi_class='auto',solver='liblinear')

In [76]:
classification.fit(X_train,y_train)

LogisticRegression(C=1, penalty='l1', solver='liblinear')

In [77]:
y_pred=classification.predict(X_test)

In [78]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

In [81]:
classification.predict_proba(X_test)

array([[6.55485130e-04, 9.99344515e-01],
       [4.89430167e-03, 9.95105698e-01],
       [4.81624017e-03, 9.95183760e-01],
       [9.66493253e-01, 3.35067473e-02],
       [9.80484987e-01, 1.95150134e-02],
       [9.82772927e-01, 1.72270734e-02],
       [9.97179590e-01, 2.82040951e-03],
       [1.05864823e-02, 9.89413518e-01],
       [9.91487093e-01, 8.51290652e-03],
       [9.89558512e-01, 1.04414879e-02],
       [9.88526748e-01, 1.14732518e-02],
       [9.55233781e-01, 4.47662191e-02],
       [2.44100304e-03, 9.97558997e-01],
       [9.98008421e-01, 1.99157913e-03],
       [3.40289891e-03, 9.96597101e-01],
       [9.91751005e-01, 8.24899522e-03],
       [1.86510834e-03, 9.98134892e-01],
       [1.75052825e-03, 9.98249472e-01],
       [9.66493253e-01, 3.35067473e-02],
       [9.82772927e-01, 1.72270734e-02]])

In [82]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [83]:
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[12  0]
 [ 0  8]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

